using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace TUKD.API.Interface
{
    public interface IUow
    {
        IDpdetRepo DpdetRepo { get; set; }
        IDpRepo DpRepo { get; set; }
        IAuthRepo AuthRepo { get; set; }
        IWebgroupRepo WebgroupRepo { get; set; }
        ITahunRepo TahunRepo { get; set; }
        IWebuserRepo WebuserRepo { get; set; }
        IWebotorRepo WebotorRepo { get; set; }
        IMenuRepo MenuRepo { get; set; }
        IWebroleRepo WebroleRepo { get; set; }
        IDafturusRepo DafturusRepo { get; set; }
        IDaftunitRepo DaftunitRepo { get; set; }
        IRkabRepo RkabRepo { get; set; }
        IRkadetbRepo RkadetbRepo { get; set; }
        IRkadanabRepo RkadanabRepo { get; set; }
        IRkadRepo RkadRepo { get; set; }
        IRkadetdRepo RkadetdRepo { get; set; }
        IRkadanadRepo RkadanadRepo { get; set; }
        IRkarRepo RkarRepo { get; set; }
        IRkadetrRepo RkadetrRepo { get; set; }
        IRkadanarRepo RkadanarRepo { get; set; }
        IDpaRepo DpaRepo { get; set; }
        IDpabRepo DpabRepo { get; set; }
        IDpablnbRepo DpablnbRepo { get; set; }
        IDpadetbRepo DpadetbRepo { get; set; }
        IDpadanabRepo DpadanabRepo { get; set; }
        IDpadRepo DpadRepo { get; set; }
        IDpablndRepo DpablndRepo { get; set; }
        IDpadetdRepo DpadetdRepo { get; set; }
        IDpadanadRepo DpadanadRepo { get; set; }
        IDparRepo DparRepo { get; set; }
        IDpablnrRepo DpablnrRepo { get; set; }
        IDpadetrRepo DpadetrRepo { get; set; }
        IDpadanarRepo DpadanarRepo { get; set; }
        IDaftrekeningRepo DaftrekeningRepo { get; set; }
        IMkegiatanRepo MkegiatanRepo { get; set; }
        IJdanaRepo JdanaRepo { get; set; }
        IStdhargaRepo StdhargaRepo { get; set; }
        IUrusanunitRepo UrusanunitRepo { get; set; }
        IMpgrmRepo MpgrmRepo { get; set; }
        IKegunitRepo KegunitRepo { get; set; }
        IPgrmunitRepo PgrmunitRepo { get; set; }
        IBulanRepo BulanRepo { get; set; }
        IJsatuanRepo JsatuanRepo { get; set; }
        ISpdRepo SpdRepo { get; set; }
        ISpddetbRepo SpddetbRepo { get; set; }
        ISpddetrRepo SpddetrRepo { get; set; }
        IDaftbankRepo DaftbankRepo { get; set; }
        IJusahaRepo JusahaRepo { get; set; }
        IDaftphk3Repo Daftphk3Repo { get; set; }
        IJbankRepo JbankRepo { get; set; }
        IKontrakRepo KontrakRepo { get; set; }
        IKontrakdetrRepo KontrakdetrRepo { get; set; }
        IStattrsRepo StattrsRepo { get; set; }
        ITagihanRepo TagihanRepo { get; set; }
        ITagihandetRepo TagihandetRepo { get; set; }
        IJtermorlunRepo JtermorlunRepo { get; set; }
        IPegawaiRepo PegawaiRepo { get; set; }
        ISifatkegRepo SifatkegRepo { get; set; }
        IDpaprogramRepo DpaprogramRepo { get; set; }
        IDpakegiatanRepo DpakegiatanRepo { get; set; }
        IJabttdRepo JabttdRepo { get; set; }
        IDaftdokRepo DaftdokRepo { get; set; }
        IPemdaRepo PemdaRepo { get; set; }
        IGolonganRepo GolonganRepo { get; set; }
        IJbendRepo JbendRepo { get; set; }
        IBendRepo BendRepo { get; set; }
        ITahapRepo TahapRepo { get; set; }
        IPaguskpdRepo PaguskpdRepo { get; set; }
        IBkbkasRepo BkbkasRepo { get; set; }
        IStrurekRepo StrurekRepo { get; set; }
        ISppRepo SppRepo { get; set; }
        ISpptagRepo SpptagRepo { get; set; }
        IZkodeRepo ZkodeRepo { get; set; }
        ISppdetbRepo SppdetbRepo { get; set; }
        IJtrnlkasRepo JtrnlkasRepo { get; set; }
        IJkegRepo JkegRepo { get; set; }
        ISppdetrRepo SppdetrRepo { get; set; }
        IAdendumRepo AdendumRepo { get; set; }
        ISpjRepo SpjRepo { get; set; }
        ISpjsppRepo SpjsppRepo { get; set; }
        IBpkspjRepo BpkspjRepo { get; set; }
        IBpkdetrRepo BpkdetrRepo { get; set; }
        ISpmRepo SpmRepo { get; set; }
        IJnspajakRepo JnspajakRepo { get; set; }
        IPajakRepo PajakRepo { get; set; }
        ISppdetrpRepo SppdetrpRepo { get; set; }
        ISp2dRepo Sp2dRepo { get; set; }
        IBpkRepo BpkRepo { get; set; }
        IJbayarRepo JbayarRepo { get; set; }
        IJtransferRepo JtransferRepo { get; set; }
        ISp2dbpkRepo Sp2dbpkRepo { get; set; }
        IBkbankRepo BkbankRepo { get; set; }
        IBkbankdetRepo BkbankdetRepo { get; set; }
        ITbpRepo TbpRepo { get; set; }
        ITbpdetbRepo TbpdetbRepo { get; set; }
        ITbpdettRepo TbpdettRepo { get; set; }
        ITbpdetdRepo TbpdetdRepo { get; set; }
        ITbpdettkegRepo TbpdettkegRepo { get; set; }
        ITbplRepo TbplRepo { get; set; }
        ITbpldetRepo TbpldetRepo { get; set; }
        ITbpldetkegRepo TbpldetkegRepo { get; set; }
        ITbpdetrRepo TbpdetrRepo { get; set; }
        IBkubankRepo BkubankRepo { get; set; }
        IBkubpkRepo BkubpkRepo { get; set; }
        IBkudRepo BkudRepo { get; set; }
        IBkukRepo BkukRepo { get; set; }
        IBkupajakRepo BkupajakRepo { get; set; }
        IBkusp2dRepo Bkusp2DRepo { get; set; }
        IBkustsRepo BkustsRepo { get; set; }
        IBkutbpRepo BkutbpRepo { get; set; }
        IBpkpajakRepo BpkpajakRepo { get; set; }
        IPanjarRepo PanjarRepo { get; set; }
        IPanjardetRepo PanjardetRepo { get; set; }
        IBkupanjarRepo BkupanjarRepo { get; set; }
        IBkuRepo BkuRepo { get; set; }
        IBkpajakRepo BkpajakRepo { get; set; }
        IBkpajakdetstrRepo BkpajakdetstrRepo { get; set; }
        ISkpRepo SkpRepo { get; set; }
        ISkpdetRepo SkpdetRepo { get; set; }
        IStsRepo StsRepo { get; set; }
        IStsdetbRepo StsdetbRepo { get; set; }
        IStsdettRepo StsdettRepo { get; set; }
        IStsdetdRepo StsdetdRepo { get; set; }
        IStsdetrRepo StsdetrRepo { get; set; }
        ITbpstsRepo TbpstsRepo { get; set; }
        ISkpstsRepo SkpstsRepo { get; set; }
        IJbmRepo JbmRepo { get; set; } 
        IBktmemRepo BktmemRepo { get; set; }
        IBktmemdetrRepo BktmemdetrRepo { get; set; }
        IBktmemdetdRepo BktmemdetdRepo { get; set; }
        IBktmemdetbRepo BktmemdetbRepo { get; set; }
        IBktmemdetnRepo BktmemdetnRepo { get; set; }
        IJnsakunRepo JnsakunRepo { get; set; }
        IJurnalRepo JurnalRepo { get; set; }
        IPrognosisbRepo PrognosisbRepo { get; set; }
        IPrognosisdRepo PrognosisdRepo { get; set; }
        IPrognosisrRepo PrognosisrRepo { get; set; }
        ISaldoawallraRepo SaldoawallraRepo { get; set; }
        ISaldoawalnrcRepo SaldoawalnrcRepo { get; set; }
        ISaldoawalloRepo SaldoawalloRepo { get; set; }
        IJnslakRepo JnslakRepo { get; set; }
        IDaftreklakRepo DaftreklakRepo { get; set; } 
        ILpjRepo LpjRepo { get; set; }
        ISpjlpjRepo SpjlpjRepo { get; set; }
        ISpjtrRepo SpjtrRepo { get; set; }
        IBkutbpspjtrRepo BkutbpspjtrRepo { get; set; }
        IBkustsspjtrRepo BkustsspjtrRepo { get; set; }
        ISpmdetdRepo SpmdetdRepo { get; set; }
        ISpmdetbRepo SpmdetbRepo { get; set; }
        IJbkasRepo JbkasRepo { get; set; }
        IJkinkegRepo JkinkegRepo { get; set; }
        IKinkegRepo KinkegRepo { get; set; }
        IKegsbdanaRepo KegsbdanaRepo { get; set; }
        IRkatapdbRepo RkatapdbRepo { get; set; }
        IRkatapddRepo RkatapddRepo { get; set; }
        IRkatapdrRepo RkatapdrRepo { get; set; }
        IRkatapddetbRepo RkatapddetbRepo { get; set; }
        IRkatapddetdRepo RkatapddetdRepo { get; set; }
        IRkatapddetrRepo RkatapddetrRepo { get; set; }
        IRkasahRepo RkasahRepo { get; set; }
        IWebsetRepo WebsetRepo { get; set; }
        ICheckdokRepo CheckdokRepo { get; set; }
        ISppcheckdokRepo SppcheckdokRepo { get; set; }
        IStruunitRepo StruunitRepo { get; set; }
        IJrekRepo JrekRepo { get; set; }
        IBpkpajakdetRepo BpkpajakdetRepo { get; set; }
        IBpkpajakstrRepo BpkpajakstrRepo { get; set; }
        IBpkpajakstrdetRepo BpkpajakstrdetRepo { get; set; }
        ISp2dcheckdokRepo Sp2DcheckdokRepo { get; set; }
        ISp2dNtpnRepo Sp2dNtpnRepo { get; set; }
        ISkptbpRepo SkptbpRepo { get; set; }
        Task<bool> Complete();
    }
}
